version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tests
      MYSQL_USER: netsu
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
